# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
exclude: '.patch$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-added-large-files
        args: [--maxkb=50, --enforce-all] # increase or add git lfs if too strict
        exclude: MODULE.bazel.lock

  - repo: https://github.com/eclipse-score/tooling
    rev: 31ff8eee214e4e97ef8f5cb46e443273515b63ec
    hooks:
      - id: copyright

  - repo: https://codeberg.org/fsfe/reuse-tool
    rev: a1bb792acda6fd0724936b4ebbdbc8eceb9c0459 # v6.2.0
    hooks:
      - id: reuse-lint-file

  - repo: https://github.com/google/yamlfmt
    rev: 21ca5323a9c87ee37a434e0ca908efc0a89daa07 # v0.21.0
    hooks:
      - id: yamlfmt

  - repo: local
    hooks:
      - id: bzlmod-tidy
        name: bazel mod tidy
        entry: bazel mod tidy
        language: system
        pass_filenames: false
      - id: bzlmod-lockfile
        name: bazel mod deps lockfile check
        entry: bazel mod deps --lockfile_mode=error
        language: system
        pass_filenames: false
